### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [cj-support/CJ-Affiliate-Conversion#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1. encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string.  You should use this method wherever applicable.
var cjSrc = 'https://www.emjcd.com/u?CID=' + companyID + '&OID=' + orderID + '&TYPE=' + actionID + '&CURRENCY=USD&'+ eventID + '&COUPON='+ coupon + '&DISCOUNT=' + wholeOrderDiscount + '&METHOD=IMG';

cjSrc += '&ITEM' + j.toString() + '=' + skuList[i] + '&AMT' + j.toString() + '=' + priceList[i] + '&QTY' + j.toString() + '=' + quantityList[i];

cjSrc += '&ITEM1=' + sku + '&AMT1=' + orderSubTotal + '&QTY1=' + quantity;

2. When we run the tests we are seeing an error for gtmonsuccess. Please resolve the issue
![cj-affliate_Error](https://user-images.githubusercontent.com/53495700/86173068-3c8e1900-bad4-11ea-8051-0dfc09baa5d2.png)

**Comment by mattyEyes** [comment]
Issues resolved, updated template.tpl in repo.
